name: Deploy GitHub Pages - Manual Fix

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/pages.yml
    with:
      manual_deployment: true
    secrets: inherit
